# Generated by Django 3.1.1 on 2020-10-22 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poem', '0002_auto_20201022_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='poem_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
